name: KIN HF Deploy

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install huggingface_hub
      - run: python kin-deploy/deploy_kin.py
