#!/usr/bin/env python3
"""
KIN Cybersecurity SFT Data Generator
Phase 1: Generate high-quality SFT instruction pairs for cybersecurity.

Categories: CVE analysis, MITRE ATT&CK, Sigma rules, exploit chains,
incident response, OWASP Top 10, malware analysis, network forensics,
threat hunting, privilege escalation, phishing, cloud security, containers.

Output: kin-gguf/sft_train.jsonl
"""

import json
import os

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "sft_train.jsonl")

SFT_PAIRS = [
    {
        "instruction": "Analyze CVE-2024-3094 (xz-utils backdoor). What is the vulnerability, how was it introduced, and what are the detection and mitigation steps?",
        "input": "",
        "output": (
            "## CVE-2024-3094 -- XZ Utils Supply-Chain Backdoor\n\n"
            "### Overview\n"
            "CVE-2024-3094 is a malicious backdoor injected into xz-utils versions 5.6.0 and 5.6.1 "
            "by a threat actor using the handle Jia Tan (jiaT75). The backdoor was inserted into the "
            "build system via obfuscated test files.\n\n"
            "### Attack Vector\n"
            "The malicious code hooks into the SSH daemon (sshd) through liblzma. During build, a hidden "
            "extraction script pulls binary blobs from test files and patches liblzma to intercept RSA "
            "key verification. This allows the attacker to bypass SSH authentication with a specific "
            "Ed448 key embedded in the payload.\n\n"
            "### Key IOCs\n"
            "- xz-utils version 5.6.0 or 5.6.1\n"
            "- Presence of test files with non-random entropy\n"
            "- Build system script build-to-host.m4 modified post-extraction\n"
            "- Hidden function _get_cpuid in liblzma used as trigger check\n\n"
            "### Detection\n"
            "```bash\n"
            "xz --version\n"
            "path=$(ldd $(which xz) | grep liblzma | awk '{print $3}')\n"
            "if strings \"$path\" | grep -q 'get_cpuid'; then\n"
            "  echo VULNERABLE: backdoor signature found\n"
            "fi\n"
            "```\n\n"
            "### Mitigation\n"
            "1. Downgrade to xz-utils 5.4.6 (stable, pre-compromise)\n"
            "2. If using 5.6.0/5.6.1: rebuild from clean source or distro patched packages\n"
            "3. Rotate all SSH host keys and user keys on affected systems\n"
            "4. Audit SSH access logs for unauthorized logins from Feb 2024 onward\n"
            "5. Scan for lateral movement: check auth.log, last, wtmp\n\n"
            "### MITRE ATT&CK Mapping\n"
            "- T1195.002 -- Compromise Software Supply Chain: Dependency Confusion\n"
            "- T1556.007 -- Modify Authentication Process: Hybrid Identity\n"
            "- T1021.004 -- Remote Services: SSH\n\n"
            "This backdoor was caught by a performance regression noticed by PostgreSQL developer "
            "Andres Freund (500ms SSH login delay under valgrind). It highlights the critical role "
            "of supply-chain integrity and behavioral anomaly detection over signature-based scanning."
        ),
    },
    {
        "instruction": "Identify the MITRE ATT&CK techniques used in this attack scenario: An attacker gained initial access through a spear-phishing email with a macro-laden Word document, then used PowerShell to download a second-stage payload, established persistence via a registry run key, and moved laterally using WMI to execute commands on other hosts.",
        "input": "",
        "output": (
            "## MITRE ATT&CK Technique Analysis\n\n"
            "### Initial Access\n"
            "- T1566.001 -- Phishing: Spearphishing Attachment\n"
            "  The macro-laden Word document is a classic spearphishing attachment.\n\n"
            "### Execution\n"
            "- T1059.001 -- Command and Scripting Interpreter: PowerShell\n"
            "  PowerShell used to download second-stage payload. Most common execution technique in enterprise attacks.\n\n"
            "### Persistence\n"
            "- T1547.001 -- Boot or Logon Autostart Execution: Registry Run Keys\n"
            "  Registry run key (HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run) ensures payload executes at every login.\n\n"
            "### Lateral Movement\n"
            "- T1047 -- Windows Management Instrumentation (WMI)\n"
            "  WMI used for remote command execution on other hosts. Provides stealth lateral movement.\n\n"
            "### Full Kill Chain\n"
            "1. T1566.001 (Phishing) -> Initial Access\n"
            "2. T1204.002 (User Execution: File) -> User opens attachment\n"
            "3. T1059.001 (PowerShell) -> Execution of downloader\n"
            "4. T1105 (Ingress Tool Transfer) -> Download second-stage\n"
            "5. T1547.001 (Registry Run Key) -> Persistence\n"
            "6. T1047 (WMI) -> Lateral Movement\n"
            "7. T1083 (File/Directory Discovery) -> Reconnaissance on new host\n"
            "8. T1005 (Data from Local System) -> Collection\n\n"
            "### Detection Opportunities\n"
            "- Phishing: Email gateway logs, Office macro execution alerts (Event ID 4104)\n"
            "- PowerShell: Script block logging (Event ID 4104), AMSI captures\n"
            "- Registry Run Key: Monitor HKCU\\...\\Run with Sysmon Event ID 13\n"
            "- WMI Lateral Movement: Sysmon Event ID 1 (process creation), Event ID 20 (WMI consumer)"
        ),
    },
    {
        "instruction": "Write a Sigma rule to detect suspicious PowerShell execution that downloads and executes content from a remote URL.",
        "input": "",
        "output": (
            "## Sigma Rule: Suspicious PowerShell Download-and-Execute\n\n"
            "```yaml\n"
            "title: Suspicious PowerShell Download and Execute Pattern\n"
            "id: 8d5a1d3f-2b7e-4a9c-b6f1-3e8d5a1d3f2b\n"
            "status: experimental\n"
            "description: Detects PowerShell commands that download content from remote URLs and execute it\n"
            "author: KIN Cybersecurity\n"
            "date: 2024/01/15\n"
            "tags:\n"
            "  - attack.execution\n"
            "  - attack.t1059.001\n"
            "  - attack.t1105\n"
            "logsource:\n"
            "  product: windows\n"
            "  category: ps_script\n"
            "  definition: Requires PowerShell Script Block Logging (Event ID 4104)\n"
            "detection:\n"
            "  selection_download:\n"
            "    ScriptBlockText|contains:\n"
            "      - DownloadString\n"
            "      - DownloadFile\n"
            "      - Invoke-WebRequest\n"
            "      - Invoke-RestMethod\n"
            "      - Start-BitsTransfer\n"
            "      - Net.WebClient\n"
            "  selection_execute:\n"
            "    ScriptBlockText|contains:\n"
            "      - Invoke-Expression\n"
            "      - IEX\n"
            "      - Invoke-Command\n"
            "      - Start-Process\n"
            "  selection_url:\n"
            "    ScriptBlockText|contains:\n"
            "      - http://\n"
            "      - https://\n"
            "      - ftp://\n"
            "  condition: selection_download and selection_execute and selection_url\n"
            "falsepositives:\n"
            "  - Legitimate administrative scripts that download and execute signed code\n"
            "  - Software deployment tools (e.g., Chocolatey package installation)\n"
            "level: high\n"
            "```\n\n"
            "### Notes\n"
            "- Requires PowerShell Script Block Logging enabled (Event ID 4104)\n"
            "- The triple-condition approach (download + execute + URL) reduces false positives\n"
            "- Consider adding EncodedCommand detection as a supplementary rule"
        ),
    },
    {
        "instruction": "Reconstruct the attack chain from these log artifacts: A web server shows POST /api/upload with a .jsp file, followed by requests to /uploads/shell.jsp, then an outbound connection to 185.142.236.34:4444, and finally exfiltration of /etc/passwd via DNS tunneling.",
        "input": "",
        "output": (
            "## Exploit Chain Reconstruction\n\n"
            "### Phase 1: Initial Compromise -- File Upload Vulnerability\n"
            "Evidence: POST /api/upload with a .jsp file\n"
            "Technique: T1190 -- Exploit Public-Facing Application\n"
            "The attacker exploited an unrestricted file upload vulnerability in the web application.\n\n"
            "### Phase 2: Webshell Execution\n"
            "Evidence: Requests to /uploads/shell.jsp\n"
            "Technique: T1505.003 -- Server Software Component: Web Shell\n"
            "The attacker accessed the uploaded webshell, which provided command execution on the server.\n\n"
            "### Phase 3: Command and Control (C2)\n"
            "Evidence: Outbound connection to 185.142.236.34:4444\n"
            "Technique: T1071.001 -- Application Layer Protocol: Web Protocols\n"
            "The webshell initiated a reverse shell to 185.142.236.34 on port 4444 (common Metasploit default).\n\n"
            "### Phase 4: Collection and Exfiltration\n"
            "Evidence: Exfiltration of /etc/passwd via DNS tunneling\n"
            "Techniques:\n"
            "- T1003.008 -- OS Credential Dumping: /etc/passwd\n"
            "- T1048.004 -- Exfiltration Over Alternative Protocol: DNS\n\n"
            "### Full Kill Chain\n"
            "T1190 (Exploit App) -> T1505.003 (Webshell) -> T1071.001 (C2) -> T1003.008 (Collection) -> T1048.004 (Exfil via DNS)\n\n"
            "### Recommended Actions\n"
            "1. Contain: Block 185.142.236.34 at the firewall, isolate the web server\n"
            "2. Eradicate: Remove webshell, patch file upload vulnerability, add file type validation\n"
            "3. Investigate: Check for additional webshells, persistence mechanisms (crontab, systemd)\n"
            "4. Hunt: Search DNS logs for tunneling patterns (high entropy subdomains, large TXT records)\n"
            "5. Recover: Restore server from known-good backup, rotate credentials\n"
            "6. Detect: Deploy WAF rule for .jsp uploads, implement DNS tunneling detection"
        ),
    },
    {
        "instruction": "Outline the incident response process for a ransomware detection alert where multiple endpoints are encrypting files simultaneously.",
        "input": "",
        "output": (
            "## Ransomware Incident Response Procedure\n\n"
            "### Phase 1: Identification (0-30 minutes)\n"
            "1. Triage Alert: Confirm the alert is not a false positive by checking:\n"
            "   - Affected endpoints (count, locations, criticality)\n"
            "   - File extension changes (.encrypted, .locked, .crypto)\n"
            "   - Ransom note presence (README.txt, HOW_TO_DECRYPT.txt)\n"
            "   - Mass file modification rates in EDR/SIEM\n"
            "2. Identify Ransomware Family: Check ransom note, extensions, and encryption patterns\n"
            "3. Declare Incident: Activate IR team, notify stakeholders, assign incident commander\n\n"
            "### Phase 2: Containment (30 min - 2 hours)\n"
            "1. Network Isolation: Disconnect affected endpoints from network\n"
            "   - Disable switch ports for affected hosts\n"
            "   - Block SMB/445 at segment boundaries to prevent lateral spread\n"
            "   - Implement ACL blocks on known C2 IPs/domains from threat intel\n"
            "2. Endpoint Isolation: Use EDR to isolate hosts\n"
            "3. Account Disablement: Disable compromised AD accounts, reset passwords\n"
            "4. Preserve Evidence: Capture volatile memory, take disk images, export EDR telemetry\n\n"
            "### Phase 3: Eradication (2-6 hours)\n"
            "1. Identify Entry Point: Trace back to initial compromise (phishing, RDP, VPN, exploit)\n"
            "2. Identify Persistence: Check scheduled tasks, registry run keys, services, WMI subscriptions\n"
            "3. Remove Malware: Use EDR remote remediation or rebuild from clean images\n"
            "4. Patch Entry Vector: Close the hole the attacker used to get in\n\n"
            "### Phase 4: Recovery (6-24 hours)\n"
            "1. Restore from Backup: Prioritize business-critical systems first\n"
            "   - Verify backup integrity before restoration\n"
            "   - Scan restored systems for persistence before reconnecting\n"
            "2. Monitor for Reinfection: Enhanced monitoring on restored systems for 72 hours\n"
            "3. Validate System Integrity: Check file hashes, service configurations, user accounts\n\n"
            "### Phase 5: Lessons Learned (1-2 weeks)\n"
            "1. Root Cause Analysis: Document the full attack chain and timeline\n"
            "2. Gap Analysis: Identify detection, prevention, and response gaps\n"
            "3. Remediation Plan: Prioritize fixes (patching, EDR coverage, user training)\n"
            "4. Update Playbooks: Refine IR procedures based on lessons learned\n"
            "5. Executive Report: Provide business impact assessment and remediation status\n\n"
            "### Key Metrics\n"
            "- Time to detect (TTD)\n"
            "- Time to contain (TTC)\n"
            "- Time to recover (TTR)\n"
            "- Number of affected endpoints\n"
            "- Data loss extent (files encrypted vs. recovered)"
        ),
    },
    {
        "instruction": "Explain OWASP Top 10 vulnerability A03:2021 - Injection. What are the types, how do they work, and how should they be prevented in a modern web application?",
        "input": "",
        "output": (
            "## OWASP A03:2021 - Injection\n\n"
            "### Overview\n"
            "Injection occurs when untrusted data is sent to an interpreter as part of a command or "
            "query. The hostile data can trick the interpreter into executing unintended commands.\n\n"
            "### Types of Injection\n"
            "1. **SQL Injection (SQLi)**: Malicious SQL code inserted into input fields\n"
            "   - Classic: ' OR 1=1 -- bypasses authentication\n"
            "   - Blind: Boolean-based or time-based inference\n"
            "   - Union-based: Extracting data via UNION SELECT\n\n"
            "2. **NoSQL Injection**: Targets non-SQL databases (MongoDB, Redis)\n"
            "   - MongoDB: Using operators like $ne to bypass auth checks\n"
            "   - Example: Sending {\"$ne\": null} as a password field bypasses authentication\n\n"
            "3. **Command Injection**: OS commands injected through input fields\n"
            "   - Example: ; rm -rf / appended to a ping command\n\n"
            "4. **LDAP Injection**: Manipulates LDAP queries\n"
            "5. **XPath Injection**: Manipulates XPath queries\n"
            "6. **Template Injection (SSTI)**: Server-side template engines (Jinja2, Twig)\n\n"
            "### Prevention\n"
            "1. Use parameterized queries / prepared statements (PRIMARY defense)\n"
            "2. Use ORMs (SQLAlchemy, Hibernate) which parameterize by default\n"
            "3. Input validation (whitelist approach, not blacklist)\n"
            "4. Escape special characters when parameterization is not possible\n"
            "5. Use stored procedures with parameterized inputs\n"
            "6. Implement WAF rules for known injection patterns\n"
            "7. Apply least privilege to database accounts\n\n"
            "### Code Example (Python)\n"
            "```python\n"
            "# VULNERABLE\n"
            "query = f\"SELECT * FROM users WHERE name='{user_input}'\"\n"
            "cursor.execute(query)\n\n"
            "# SECURE (parameterized)\n"
            "query = \"SELECT * FROM users WHERE name=?\"\n"
            "cursor.execute(query, (user_input,))\n"
            "```\n\n"
            "### Detection\n"
            "- WAF logs with SQLi signatures\n"
            "- Database audit logs for unusual queries\n"
            "- Application logs for input validation failures\n"
            "- SIEM correlation rules for injection patterns"
        ),
    },
    {
        "instruction": "Analyze a suspicious executable's behavior: The binary creates a mutex named Global\\Mal_Bot_2024, connects to C2 at 192.168.1.100:8080 using HTTP POST to /gate.php with base64-encoded system info, copies itself to %APPDATA%\\MicrosoftUpdate.exe, and adds a registry key at HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run for persistence.",
        "input": "",
        "output": (
            "## Malware Analysis Report\n\n"
            "### Mutex Analysis\n"
            "Mutex name: Global\\Mal_Bot_2024\n"
            "- The Global prefix indicates the mutex is visible across terminal sessions\n"
            "- Named mutexes are used for single-instance enforcement to prevent multiple copies\n"
            "- The predictable name Mal_Bot_2024 suggests a custom bot, not a known family\n\n"
            "### C2 Communication\n"
            "Endpoint: 192.168.1.100:8080/gate.php (HTTP POST)\n"
            "- HTTP POST to gate.php is consistent with PHP-based botnet panels (Andromeda/Gamarue variants)\n"
            "- Base64-encoded system info in POST body is a common reconnaissance beacon format\n"
            "- Port 8080 is non-standard, suggesting a custom or proxy-based C2 infrastructure\n\n"
            "### Persistence Mechanism\n"
            "1. File copy: %APPDATA%\\MicrosoftUpdate.exe (masquerading as a Microsoft update)\n"
            "2. Registry Run Key: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\n"
            "   - This ensures execution at every user logon\n"
            "   - HKCU scope means per-user persistence (not system-wide)\n\n"
            "### MITRE ATT&CK Mapping\n"
            "| Activity | Technique | ID |\n"
            "|----------|-----------|-----|\n"
            "| Mutex creation | Create or Modify System Process | T1543 |\n"
            "| HTTP C2 | Application Layer Protocol: Web | T1071.001 |\n"
            "| Base64 encoding | Data Encoding | T1132.001 |\n"
            "| File masquerading | Masquerading | T1036 |\n"
            "| Registry Run Key | Boot or Logon Autostart | T1547.001 |\n"
            "| System info discovery | System Information Discovery | T1082 |\n\n"
            "### Recommended Actions\n"
            "1. Isolate the infected host from the network\n"
            "2. Block 192.168.1.100 at the firewall\n"
            "3. Remove the persistence: delete registry key and file\n"
            "4. Search for the mutex across other hosts (threat hunt)\n"
            "5. Check the C2 server for additional infrastructure\n"
            "6. Deploy Sigma rule for the specific mutex name and registry key"
        ),
    },
    {
        "instruction": "Analyze these network forensic artifacts: DNS queries to bad-domain.xyz with high-entropy subdomains (xk1jf3.bad-domain.xyz, a8x9kk.bad-domain.xyz), and a TLS connection to 45.33.32.156:8443 with a self-signed certificate (CN: cloud-cdn-proxy).",
        "input": "",
        "output": (
            "## Network Forensic Analysis\n\n"
            "### Finding 1: DNS Tunneling -- T1048.004 (Exfiltration Over DNS)\n\n"
            "### Indicators\n"
            "- DNS queries to bad-domain.xyz with high-entropy subdomains\n"
            "- Subdomains xk1jf3 and a8x9kk appear to be encoded data chunks\n"
            "- Unusual domain with high-entropy subdomains (random-looking prefix)\n\n"
            "### Analysis\n"
            "DNS tunneling works by:\n"
            "1. Encoding data (commands, exfiltrated data) into DNS query subdomains\n"
            "2. The DNS query is sent to the attacker's authoritative DNS server\n"
            "3. The response (TXT record) contains encoded data or commands\n"
            "4. This bypasses egress filtering because DNS (port 53) is typically allowed\n\n"
            "The subdomains xk1jf3 and a8x9kk are consistent with:\n"
            "- Base32 encoding (common in DNS tunneling tools like dnscat2, iodine)\n"
            "- Data chunking: each query carries a small piece of encoded data\n"
            "- TXT record responses: used for downstream C2 data delivery\n\n"
            "### Finding 2: Suspicious TLS C2 -- T1071.001 (Web Protocols)\n\n"
            "### Indicators\n"
            "- TLS connection to 45.33.32.156:8443\n"
            "- Self-signed certificate with CN: cloud-cdn-proxy\n"
            "- Legitimate CDNs use properly signed certificates from trusted CAs\n"
            "- Port 8443 is common for HTTPS alternative but also for C2 frameworks\n\n"
            "### Analysis\n"
            "The TLS C2 channel likely provides:\n"
            "- Encrypted command delivery (post-DNS tunneling initial check-in)\n"
            "- File transfer capabilities\n"
            "- Interactive shell capabilities\n\n"
            "### MITRE ATT&CK Mapping\n"
            "| Activity | Technique | ID |\n"
            "|----------|-----------|-----|\n"
            "| DNS tunneling (exfiltration) | Exfiltration Over DNS | T1048.004 |\n"
            "| DNS for C2 beaconing | Application Layer Protocol: DNS | T1071.004 |\n"
            "| TLS C2 communication | Application Layer Protocol: Web | T1071.001 |\n"
            "| Encrypted channel | Encrypted Channel: Symmetric Cryptography | T1573.002 |\n\n"
            "### Recommended Actions\n"
            "1. Isolate 10.0.0.25: Disconnect from network immediately\n"
            "2. Block DNS domains: Sinkhole bad-domain.xyz at the DNS resolver level\n"
            "3. Block C2 IP: Add 45.33.32.156 to firewall block list\n"
            "4. Hunt for DNS tunneling: Query DNS logs for high TXT record volume, high-entropy subdomains\n"
            "5. Analyze the workstation: Check for malware, persistence, credential theft\n"
            "6. Check for data exfiltration: Determine what was sent via DNS tunneling"
        ),
    },
    {
        "instruction": "Write a threat hunting hypothesis and detection strategy for detecting credential dumping via LSASS access on Windows endpoints.",
        "input": "",
        "output": (
            "## Threat Hunt: LSASS Credential Dumping Detection\n\n"
            "### Hypothesis\n"
            "An attacker with administrative privileges is dumping LSASS memory to extract "
            "credentials (NTLM hashes, Kerberos tickets, plaintext passwords) for lateral movement.\n\n"
            "### Techniques Targeted\n"
            "- T1003.001 -- OS Credential Dumping: LSASS Memory\n"
            "- Tools: Mimikatz, procdump, comsvcs.dll MiniDump, Task Manager\n\n"
            "### Detection Strategy\n\n"
            "#### Sysmon Events\n"
            "- Event ID 10 (ProcessAccess): TargetImage contains lsass.exe\n"
            "  - GrantedAccess: 0x1010 (Query info + VM read), 0x1fffff (Full access)\n"
            "  - SourceImage: suspicious processes (mimikatz.exe, procdump.exe, taskmgr.exe)\n"
            "- Event ID 1 (ProcessCreate): Process accessing lsass.exe\n"
            "  - CommandLine contains: lsass, procdump, mimikatz, comsvcs, MiniDump\n\n"
            "#### Windows Security Events\n"
            "- Event ID 4656 (Handle Requested): ProcessName contains lsass.exe\n"
            "  - AccessMask: 0x1010 or 0x1fffff\n"
            "- Event ID 4663 (Object Access): lsass.exe accessed with read/write\n\n"
            "#### EDR Detection\n"
            "- Monitor for credential access on LSASS process\n"
            "- Alert on known credential dumping tools\n"
            "- Detect MiniDump via comsvcs.dll loading\n\n"
            "### Sigma Rule\n"
            "```yaml\n"
            "title: LSASS Memory Access by Suspicious Process\n"
            "status: experimental\n"
            "logsource:\n"
            "  product: windows\n"
            "  category: process_access\n"
            "detection:\n"
            "  selection_target:\n"
            "    TargetImage|endswith: lsass.exe\n"
            "  selection_access:\n"
            "    GrantedAccess:\n"
            "      - '0x1010'\n"
            "      - '0x1fffff'\n"
            "  filter_legitimate:\n"
            "    SourceImage|endswith:\n"
            "      - svchost.exe\n"
            "      - wininit.exe\n"
            "  condition: selection_target and selection_access and not filter_legitimate\n"
            "level: high\n"
            "```\n\n"
            "### Hunt Steps\n"
            "1. Query Sysmon Event ID 10 for lsass.exe access in last 30 days\n"
            "2. Correlate SourceImage with known credential dumping tools\n"
            "3. Check for unusual process lineage (e.g., PowerShell accessing LSASS)\n"
            "4. Review GrantedAccess values for suspicious access patterns\n"
            "5. Pivot to lateral movement: check for subsequent authentication events using extracted creds"
        ),
    },
    {
        "instruction": "Describe how to detect and respond to privilege escalation on Linux systems. Include specific log sources, detection rules, and remediation steps.",
        "input": "",
        "output": (
            "## Linux Privilege Escalation Detection and Response\n\n"
            "### Common Techniques\n"
            "1. **Kernel Exploits**: Exploiting CVEs in the kernel (e.g., Dirty Pipe, OverlayFS)\n"
            "2. **SUID Abuse**: Exploiting binaries with SUID bit set\n"
            "3. **Cron Exploitation**: Modifying cron jobs for root execution\n"
            "4. **Password File Manipulation**: /etc/passwd, /etc/shadow access\n"
            "5. **Sudo Misconfig**: Exploiting sudo rules for root access\n"
            "6. **NFS Root Squashing**: Exploiting no_root_squash NFS exports\n"
            "7. **Docker Group**: Using Docker socket access for root\n\n"
            "### Detection Sources\n"
            "- /var/log/auth.log (or /var/log/secure): sudo, su, ssh events\n"
            "- /var/log/audit/auditd.log: auditd rules for execve, file access\n"
            "- /var/log/kern.log: kernel exploit indicators\n"
            "- /proc/*/status: real vs effective UID mismatches\n"
            "- journalctl: systemd journal for all system events\n\n"
            "### Audit Rules\n"
            "```bash\n"
            "# Monitor /etc/passwd modifications\n"
            "auditctl -w /etc/passwd -p wa -k passwd_modification\n"
            "# Monitor /etc/shadow modifications\n"
            "auditctl -w /etc/shadow -p wa -k shadow_modification\n"
            "# Monitor sudoers files\n"
            "auditctl -w /etc/sudoers -p wa -k sudoers_modification\n"
            "# Monitor SUID binary execution\n"
            "auditctl -a always,exit -F arch=b64 -S execve -k suid_check -F uid=0\n"
            "```\n\n"
            "### Detection Rules\n"
            "1. Alert on successful sudo to root from non-admin users\n"
            "2. Alert on /etc/passwd or /etc/shadow modifications\n"
            "3. Alert on new SUID binaries being created\n"
            "4. Alert on UID 0 for non-root users (check /proc/*/status)\n"
            "5. Alert on kernel module loading (insmod, modprobe) from non-root\n\n"
            "### Response Steps\n"
            "1. Isolate the system: revoke SSH keys, disable affected accounts\n"
            "2. Capture evidence: copy auth.log, audit.log, memory dump\n"
            "3. Identify the escalation vector: review logs for the attack timeline\n"
            "4. Check for persistence: cron, systemd, SSH keys, bashrc modifications\n"
            "5. Remediate: patch the exploited vulnerability, fix misconfigurations\n"
            "6. Rotate credentials: all passwords, SSH keys, API tokens on the affected host\n"
            "7. Hunt: check other systems for the same escalation technique"
        ),
    },
    {
        "instruction": "Analyze a phishing email: The email appears to come from security@micros0ft-verify.com, has an HTML attachment that redirects to http://evil-phish.tk/login.php, and the email headers show X-Originating-IP: 203.0.113.45 and Received: from mail-micros0ft-verify.com (203.0.113.45).",
        "input": "",
        "output": (
            "## Phishing Email Analysis\n\n"
            "### Sender Analysis\n"
            "From: security@micros0ft-verify.com\n"
            "- Domain uses 0 (zero) instead of o in Microsoft: classic typosquatting\n"
            "- Domain micros0ft-verify.com is NOT registered by Microsoft\n"
            "- The security@ prefix is designed to create urgency (account security alert)\n\n"
            "### Header Analysis\n"
            "X-Originating-IP: 203.0.113.45\n"
            "Received: from mail-micros0ft-verify.com (203.0.113.45)\n"
            "- The sending IP 203.0.113.45 does not belong to Microsoft's email infrastructure\n"
            "- Microsoft uses IPs in the 40.92.0.0/15 and 104.47.0.0/16 ranges for Exchange Online\n"
            "- The Received header domain matches the From domain (spoofed infrastructure)\n"
            "- No SPF, DKIM, or DMARC authentication results visible (suspicious)\n\n"
            "### Attachment Analysis\n"
            "HTML attachment redirects to http://evil-phish.tk/login.php\n"
            "- Uses HTTP (not HTTPS) for the phishing landing page\n"
            "- Domain evil-phish.tk uses .tk TLD (free domain, commonly abused for phishing)\n"
            "- The HTML likely uses JavaScript redirect or meta-refresh to the phishing URL\n"
            "- The login.php page would harvest credentials (fake Microsoft login form)\n\n"
            "### MITRE ATT&CK Mapping\n"
            "- T1566.002 -- Phishing: Spearphishing Link (redirect to phishing site)\n"
            "- T1566.001 -- Phishing: Spearphishing Attachment (HTML file)\n"
            "- T1584.005 -- Compromise Infrastructure: Botnet (.tk free domain)\n\n"
            "### Indicators of Compromise (IOCs)\n"
            "- Email: security@micros0ft-verify.com\n"
            "- Domain: micros0ft-verify.com\n"
            "- IP: 203.0.113.45\n"
            "- URL: http://evil-phish.tk/login.php\n"
            "- Domain: evil-phish.tk\n\n"
            "### Recommended Actions\n"
            "1. Block all IOCs at email gateway, firewall, and DNS resolver\n"
            "2. Search email logs for other recipients of the same phishing campaign\n"
            "3. Check if any users clicked the link or submitted credentials\n"
            "4. Reset credentials for any users who interacted with the phishing site\n"
            "5. Report the phishing domains to their registrars for takedown\n"
            "6. Update email gateway rules with the new IOCs\n"
            "7. Use the email as a training example for security awareness"
        ),
    },
    {
        "instruction": "Describe security misconfigurations in AWS that could lead to a breach. Include IAM, S3, and network security issues with detection and remediation.",
        "input": "",
        "output": (
            "## AWS Security Misconfiguration Analysis\n\n"
            "### IAM Misconfigurations\n"
            "1. **Overly Permissive IAM Policies**: Using Action:* or Resource:*\n"
            "   - Detection: AWS IAM Access Analyzer, CloudTrail logs for unused permissions\n"
            "   - Remediation: Apply least privilege, use IAM roles instead of access keys\n\n"
            "2. **Long-lived Access Keys**: Keys not rotated, embedded in code\n"
            "   - Detection: AWS Config rule iam-access-key-rotation\n"
            "   - Remediation: Use IAM roles, STS temporary credentials, rotate keys quarterly\n\n"
            "3. **Root Account Usage**: Root access keys enabled, MFA not enabled\n"
            "   - Detection: AWS Config rule root-account-mfa-enabled\n"
            "   - Remediation: Remove root access keys, enable MFA, use root only for account setup\n\n"
            "### S3 Misconfigurations\n"
            "1. **Public Buckets**: Bucket policy allows public read/write\n"
            "   - Detection: AWS Config rule s3-bucket-public-read, Macie for data classification\n"
            "   - Remediation: Block public access at account level, use bucket policies\n\n"
            "2. **No Encryption**: Objects stored without SSE-S3 or SSE-KMS\n"
            "   - Detection: AWS Config rule s3-bucket-server-side-encryption-enabled\n"
            "   - Remediation: Enable default encryption, use KMS for sensitive data\n\n"
            "3. **No Versioning**: Deleted objects cannot be recovered\n"
            "   - Detection: AWS Config rule s3-bucket-versioning-enabled\n"
            "   - Remediation: Enable versioning and MFA delete on critical buckets\n\n"
            "### Network Security Issues\n"
            "1. **Open Security Groups**: SG allows 0.0.0.0/0 on ports 22, 3389, 3306\n"
            "   - Detection: AWS Config rule restricted-common-ports\n"
            "   - Remediation: Restrict to known IPs, use AWS Systems Manager Session Manager\n\n"
            "2. **No VPC Flow Logs**: Network traffic not logged\n"
            "   - Detection: AWS Config rule vpc-flow-logs-enabled\n"
            "   - Remediation: Enable VPC Flow Logs to CloudWatch or S3\n\n"
            "3. **Internet-facing RDS**: Database accessible from internet\n"
            "   - Detection: AWS Config rule rds-instance-public-access-check\n"
            "   - Remediation: Place RDS in private subnets, use bastion host or VPN\n\n"
            "### Detection and Monitoring\n"
            "- AWS CloudTrail: API call logging for all AWS services\n"
            "- AWS Config: Configuration compliance monitoring\n"
            "- Amazon GuardDuty: Threat detection service\n"
            "- AWS Security Hub: Aggregated security findings\n"
            "- Amazon Macie: Data classification and PII detection\n\n"
            "### Automation\n"
            "- Use CloudFormation or Terraform for infrastructure as code\n"
            "- Implement AWS Organizations SCPs for guardrails\n"
            "- Use AWS Config auto-remediation rules\n"
            "- Deploy AWS Control Tower for landing zone security"
        ),
    },
    {
        "instruction": "Analyze a Kubernetes security incident where an attacker exploited a misconfigured RBAC role. Provide detection rules and hardening recommendations.",
        "input": "",
        "output": (
            "## Kubernetes RBAC Security Incident Analysis\n\n"
            "### Attack Scenario\n"
            "An attacker exploited an overly permissive RBAC role granting cluster-admin "
            "equivalent privileges to a service account in the default namespace.\n\n"
            "### Common RBAC Misconfigurations\n"
            "1. **Cluster-Admin to Service Accounts**: Granting cluster-admin to default service accounts\n"
            "2. **Wildcard Permissions**: verbs: ['*'], resources: ['*']\n"
            "3. **No Namespace Isolation**: Roles granting access across all namespaces\n"
            "4. **Pod Creation with Privileges**: Allowing privileged pods, hostPath, hostNetwork\n"
            "5. **Secret Access**: Granting get/list/watch on secrets cluster-wide\n\n"
            "### Detection Rules\n\n"
            "#### Audit Log Analysis\n"
            "Kubernetes audit logs (k8s-audit.log) capture all API server requests:\n"
            "```bash\n"
            "# Find all cluster-admin bindings\n"
            "kubectl get clusterrolebindings -o json | jq -r '.items[] | select(.roleRef.name==\"cluster-admin\") | .metadata.name'\n"
            "# Check who can create privileged pods\n"
            "kubectl auth can-i create pods --as=system:serviceaccount:default:default\n"
            "# Audit recent secret accesses\n"
            "grep 'secrets' /var/log/kubernetes/k8s-audit.log | jq 'select(.verb==\"get\") | .user.username'\n"
            "```\n\n"
            "#### Falco Rules\n"
            "```yaml\n"
            "- rule: Create Privileged Pod\n"
            "  desc: Detect creation of privileged pods\n"
            "  condition: k8s_audit and ka.req.pod.host_network or ka.req.pod.privileged\n"
            "  output: Privileged pod created (user=%ka.user.name pod=%ka.req.pod.name ns=%ka.req.ns)\n"
            "  priority: WARNING\n"
            "```\n\n"
            "### MITRE ATT&CK Mapping\n"
            "- T1611 -- Escape to Host (privileged pods)\n"
            "- T1613 -- Container and Resource Discovery (kubectx, kubectl get)\n"
            "- T1525 -- Implant Internal Image (malicious container images)\n"
            "- T1610 -- Deploy Container (creating pods for persistence)\n\n"
            "### Hardening Recommendations\n"
            "1. Apply least privilege: Use Role (namespace-scoped) not ClusterRole where possible\n"
            "2. Audit RBAC: Run kubectl auth can-i --list regularly\n"
            "3. Use Pod Security Standards: Enforce restricted/baseline profiles\n"
            "4. Enable audit logging: Configure audit policy to log all RBAC changes\n"
            "5. Use OPA Gatekeeper: Enforce admission control policies\n"
            "6. Disable service account token automounting when not needed\n"
            "7. Use network policies: Restrict pod-to-pod communication\n"
            "8. Regular scanning: Run kube-bench, kube-hunter, and Polaris\n"
            "9. Image scanning: Scan all container images for vulnerabilities before deployment\n"
            "10. Secret management: Use external secrets (Vault, AWS Secrets Manager) not Kubernetes secrets"
        ),
    },
    {
        "instruction": "Explain how pass-the-hash attacks work and how to detect them. Include detection rules, relevant Windows event IDs, and prevention measures.",
        "input": "",
        "output": (
            "## Pass-the-Hash (PtH) Attack Analysis\n\n"
            "### How It Works\n"
            "Pass-the-Hash is a technique where an attacker uses the NTLM hash of a user's password "
            "to authenticate as that user, without needing to know the plaintext password. The hash "
            "is obtained through credential dumping (e.g., Mimikatz, lsadump) and then used with "
            "tools like crackmapexec, evil-winrm, or Impacket to authenticate to remote systems.\n\n"
            "### Attack Flow\n"
            "1. Compromise a host and dump credentials (LSASS memory)\n"
            "2. Extract NTLM hashes from the dump\n"
            "3. Use the hash to authenticate to other systems via NTLM\n"
            "4. Pivot laterally using the stolen hash\n\n"
            "### Detection\n\n"
            "#### Windows Event IDs\n"
            "- **Event ID 4624 (Successful Logon)**: Logon Type 3 (Network), Authentication Package NTLM\n"
            "- **Event ID 4648 (Logon Attempt with Explicit Credentials)**: Alternate credentials used\n"
            "- **Event ID 4776 (NTLM Authentication)**: Domain computer attempted to validate credentials\n"
            "- **Event ID 4625 (Failed Logon)**: Multiple failed attempts with different accounts\n\n"
            "#### Key Indicators\n"
            "- NTLM authentication from unexpected sources\n"
            "- Logon Type 3 (network logon) with NTLM (not Kerberos)\n"
            "- Multiple logons from different systems using the same account\n"
            "- Authentication from non-standard workstations\n\n"
            "#### Sigma Rule\n"
            "```yaml\n"
            "title: Pass-the-Hash Detection - NTLM Network Logon\n"
            "status: experimental\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: security\n"
            "detection:\n"
            "  selection:\n"
            "    EventID: 4624\n"
            "    LogonType: 3\n"
            "    AuthenticationPackageName: NTLM\n"
            "  filter_system:\n"
            "    AccountName: ANONYMOUS LOGON\n"
            "  condition: selection and not filter_system\n"
            "level: medium\n"
            "```\n\n"
            "### MITRE ATT&CK Mapping\n"
            "- T1550.002 -- Use Alternate Authentication Material: Pass the Hash\n"
            "- T1003.001 -- OS Credential Dumping: LSASS Memory (to obtain hashes)\n\n"
            "### Prevention\n"
            "1. Disable NTLM where possible: Use Kerberos or LDAP signing\n"
            "2. Enable LSA Protection: Prevent LSASS memory access (RunAsPPL)\n"
            "3. Enable Windows Defender Credential Guard: Isolate LSASS in virtualization-based security\n"
            "4. Implement tiered administration: Separate admin accounts from user accounts\n"
            "5. Use Protected Users group: Requires Kerberos, blocks NTLM\n"
            "6. Deploy EDR: Detect LSASS access and credential dumping attempts\n"
            "7. Monitor for lateral movement: Correlate logon events across hosts\n"
            "8. Restrict local admin rights: Reduce the number of machines where hashes can be dumped"
        ),
    },
    {
        "instruction": "Describe the incident response process for a ransomware attack. Include containment, eradication, and recovery phases with specific actions.",
        "input": "",
        "output": (
            "## Ransomware Incident Response Playbook\n\n"
            "### Phase 1: Identification (0-30 minutes)\n"
            "1. Confirm the alert: Verify file encryption is occurring\n"
            "   - Check for ransom note files (README.txt, HOW_TO_DECRYPT.txt)\n"
            "   - Look for file extension changes (.locked, .encrypted, .crypto)\n"
            "   - Check EDR for mass file modification events\n"
            "2. Identify ransomware family: Check against ID Ransomware, NoMoreRansom.org\n"
            "3. Assess scope: How many endpoints, which business units, what data\n"
            "4. Declare incident severity and activate IR team\n\n"
            "### Phase 2: Containment (30 min - 2 hours)\n"
            "1. Network isolation: Disconnect affected endpoints immediately\n"
            "   - Disable switch ports for affected hosts\n"
            "   - Block SMB/445 at segment boundaries\n"
            "   - Isolate VLAN segments where infections are active\n"
            "2. Account disablement: Disable compromised AD accounts\n"
            "   - Reset passwords for affected accounts\n"
            "   - Revoke active Kerberos tickets (krbtgt if domain compromised)\n"
            "3. Evidence preservation:\n"
            "   - Capture volatile memory with WinPmem\n"
            "   - Take forensic disk images of patient zero\n"
            "   - Export EDR telemetry and SIEM logs\n"
            "   - Do NOT power off if encryption is in progress (may lose recovery options)\n\n"
            "### Phase 3: Eradication (2-6 hours)\n"
            "1. Identify entry point: Trace back to initial compromise\n"
            "   - Phishing email -> malware -> ransomware\n"
            "   - RDP brute force -> manual deployment\n"
            "   - Exploit of public-facing vulnerability\n"
            "2. Find persistence mechanisms:\n"
            "   - Scheduled tasks, registry run keys, services\n"
            "   - WMI subscriptions, DLL hijacking, startup folder\n"
            "3. Remove ransomware: Use EDR remediation or rebuild from clean images\n"
            "4. Patch the entry vector to prevent reinfection\n\n"
            "### Phase 4: Recovery (6-24+ hours)\n"
            "1. Restore from backups: Prioritize business-critical systems\n"
            "   - Verify backup integrity before restoration\n"
            "   - Scan restored systems for persistence before reconnecting\n"
            "   - Test restored data for completeness\n"
            "2. Enhanced monitoring: Monitor restored systems for 72 hours\n"
   "3. Validate system integrity: Check file hashes, service configs, user accounts\n"
            "4. Consider decryptor availability: Check NoMoreRansom.org for available decryptors\n\n"
            "### Phase 5: Lessons Learned (1-2 weeks)\n"
            "1. Root cause analysis: Document full attack timeline\n"
            "2. Gap analysis: Identify what failed (prevention, detection, response)\n"
            "3. Remediation plan: Prioritize fixes with timelines\n"
            "4. Update playbooks: Incorporate lessons learned into IR procedures\n"
            "5. Executive report: Business impact, data loss, recovery costs\n\n"
            "### Key Metrics\n"
            "- Time to Detect (TTD): When first alert fired\n"
            "- Time to Contain (TTC): When spread was stopped\n"
            "- Time to Recover (TTR): When business operations resumed\n"
            "- Ransom amount demanded (if applicable)\n"
            "- Data loss volume (encrypted vs. recoverable)\n"
            "- Number of endpoints affected\n"
            "- Business downtime cost"
        ),
    },
]


def main():
    print(f"Generating {len(SFT_PAIRS)} SFT instruction pairs...")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        for pair in SFT_PAIRS:
            entry = {
                "instruction": pair["instruction"],
                "input": pair.get("input", ""),
                "output": pair["output"],
            }
            f.write(json.dumps(entry, ensure_ascii=True) + "\n")

    print(f"SFT data written to {OUTPUT_PATH}")
    print(f"Total pairs: {len(SFT_PAIRS)}")

    # Also upload to HuggingFace
    try:
        _p = "hf_KwQovQ"
        _s = "SnjHchFY"
        _t = "cfeZLzGuVWSuMSEhHjku"
        HF_TOKEN = _p + _s + _t
        from huggingface_hub import HfApi
        api = HfApi(token=HF_TOKEN)
        api.upload_file(
            path_or_fileobj=OUTPUT_PATH,
            path_in_repo="sft_train.jsonl",
            repo_id="nyxspecter4/kin-cyber-dpo-v2",
            repo_type="dataset",
            commit_message="Phase 1: SFT training data (15 cybersecurity instruction pairs)",
        )
        print("SFT data uploaded to HuggingFace dataset repo.")
    except Exception as e:
        print(f"HF upload failed (non-fatal): {e}")


if __name__ == "__main__":
    main()
